var d;
function f(a,b,c){this.extend(f,google.h.pa);this.a=a;this.b=[];this.l=[];this.sizes=[53,56,66,78,90];this.u=[];this.T=!1;c=c||{};this.m=c.gridSize||60;this.w=c.minimumClusterSize||2;this.ha=c.maxZoom||null;this.u=c.styles||[];this.za=c.imagePath||this.oa;this.ya=c.imageExtension||this.na;this.ma=!0;void 0!=c.zoomOnClick&&(this.ma=c.zoomOnClick);this.I=!1;void 0!=c.averageCenter&&(this.I=c.averageCenter);k(this);this.a=a;this.ia=this.a.ga();var e=this;google.h.event.addListener(this.a,"zoom_changed",function(){var a=
e.a.ga();e.ia!=a&&(e.ia=a,e.A())});google.h.event.addListener(this.a,"idle",function(){e.s()});b&&b.length&&this.W(b,!1)}d=f.prototype;d.oa="https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m";d.na="png";d.extend=function(a,b){return function(a){for(var b in a.prototype)this.prototype[b]=a.prototype[b];return this}.apply(a,[b])};d.S=function(){this.T||(this.T=!0,l(this))};d.O=function(){};
function k(a){if(!a.u.length)for(var b=0,c;c=a.sizes[b];b++)a.u.push({url:a.za+(b+1)+"."+a.ya,height:c,width:c})}d.sa=function(){for(var a=this.D(),b=new google.h.M,c=0,e;e=a[c];c++)b.extend(e.j());this.a.ra(b)};d.R=function(){return this.u};d.D=function(){return this.b};d.xa=function(){return this.b.length};d.Fa=function(a){this.ha=a};d.da=function(){return this.ha};d.Z=function(a,b){for(var c=0,e=a.length,g=e;0!==g;)g=parseInt(g/10,10),c++;c=Math.min(c,b);return{text:e,index:c}};
d.Da=function(a){this.Z=a};d.aa=function(){return this.Z};d.W=function(a,b){for(var c=0,e;e=a[c];c++)q(this,e);b||this.s()};function q(a,b){b.K=!1;b.draggable&&google.h.event.addListener(b,"dragend",function(){b.K=!1;a.ja()});a.b.push(b)}d.H=function(a,b){q(this,a);b||this.s()};function r(a,b){var c=-1;if(a.b.indexOf)c=a.b.indexOf(b);else for(var e=0,g;g=a.b[e];e++)if(g==b){c=e;break}if(-1==c)return!1;b.a=null;a.b.splice(c,1);return!0}
d.Ba=function(a,b){var c=r(this,a);return!b&&c?(this.A(),this.s(),!0):!1};d.Ca=function(a,b){for(var c=!1,e=0,g;g=a[e];e++)g=r(this,g),c=c||g;if(!b&&c)return this.A(),this.s(),!0};d.wa=function(){return this.l.length};d.C=function(){return this.a};d.ca=function(){return this.m};d.Ea=function(a){this.m=a};
d.P=function(a){var b=this.ua(),c=new google.h.V(a.ea().o(),a.ea().F()),e=new google.h.V(a.fa().o(),a.fa().F()),c=b.$(c);c.x+=this.m;c.y-=this.m;e=b.$(e);e.x-=this.m;e.y+=this.m;c=b.ta(c);b=b.ta(e);a.extend(c);a.extend(b);return a};d.qa=function(){this.A(!0);this.b=[]};d.A=function(a){for(var b=0,c;c=this.l[b];b++)c.remove();for(b=0;c=this.b[b];b++)c.K=!1,a&&(c.a=null);this.l=[]};
d.ja=function(){var a=this.l.slice();this.l.length=0;this.A();this.s();window.setTimeout(function(){for(var b=0,c;c=a[b];b++)c.remove()},0)};d.s=function(){l(this)};
function l(a){if(a.T)for(var b=new google.h.M(t(a.a).fa(),t(a.a).ea()),b=a.P(b),c=0,e;e=a.b[c];c++)if(!e.K&&b.contains(e.j())){var g=a,w=4E4,n=null;e.j();for(var x=0,m=void 0;m=g.l[x];x++){var h=m.ba();if(h){var p=e.j();if(h&&p)var y=(p.o()-h.o())*Math.PI/180,z=(p.F()-h.F())*Math.PI/180,h=Math.sin(y/2)*Math.sin(y/2)+Math.cos(h.o()*Math.PI/180)*Math.cos(p.o()*Math.PI/180)*Math.sin(z/2)*Math.sin(z/2),h=12742*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));else h=0;h<w&&(w=h,n=m)}}n&&n.Y.contains(e.j())?n.H(e):
(m=new u(g),m.H(e),g.l.push(m))}}function u(a){this.v=a;this.a=a.C();this.m=a.ca();this.w=a.w;this.I=a.I;this.f=null;this.b=[];this.Y=null;this.B=new v(this,a.R())}d=u.prototype;
d.H=function(a){var b;a:if(this.b.indexOf)b=-1!=this.b.indexOf(a);else{b=0;for(var c;c=this.b[b];b++)if(c==a){b=!0;break a}b=!1}if(b)return!1;this.f?this.I&&(c=this.b.length+1,b=(this.f.o()*(c-1)+a.j().o())/c,c=(this.f.F()*(c-1)+a.j().F())/c,this.f=new google.h.V(b,c),A(this)):(this.f=a.j(),A(this));a.K=!0;this.b.push(a);b=this.b.length;b<this.w&&a.C()!=this.a&&(a.a=this.a);if(b==this.w)for(c=0;c<b;c++)this.b[c].a=null;b>=this.w&&(a.a=null);a=this.a.ga();if((b=this.v.da())&&a>b)for(a=0;b=this.b[a];a++)b.a=
this.a;else this.b.length<this.w?B(this.B):(b=this.v.aa()(this.b,this.v.R().length),this.B.f=this.f,a=this.B,a.U=b,a.c&&(a.c.innerHTML=b.text),b=Math.max(0,a.U.index-1),b=Math.min(a.u.length-1,b),b=a.u[b],a.Ga=b.url,a.i=b.height,a.G=b.width,a.ka=b.textColor,a.g=b.anchor,a.la=b.textSize,a.X=b.backgroundPosition,a.J=b.iconAnchor,this.B.show());return!0};function t(a){var b=new google.h.M(a.f,a.f);a=a.D();for(var c=0,e;e=a[c];c++)b.extend(e.j());return b}
d.remove=function(){this.B.remove();this.b.length=0;delete this.b};d.va=function(){return this.b.length};d.D=function(){return this.b};d.ba=function(){return this.f};function A(a){var b=new google.h.M(a.f,a.f);a.Y=a.v.P(b)}d.C=function(){return this.a};function v(a,b){a.v.extend(v,google.h.pa);this.u=b;this.N=a;this.f=null;this.a=a.C();this.U=this.c=null;this.L=!1;this.a=this.a}d=v.prototype;
d.S=function(){this.c=document.createElement("DIV");if(this.L){var a=C(this,this.f);this.c.style.cssText=D(this,a);this.c.innerHTML=this.U.text}this.Ia().Ja.appendChild(this.c);var b=this;google.h.event.Ha(this.c,"click",function(a){var e=b.N.v;google.h.event.Ka(e,"clusterclick",b.N,a);e.ma&&b.a.ra(t(b.N))})};function C(a,b){var c=a.ua().$(b);"object"===typeof a.J&&2===a.J.length?(c.x-=a.J[0],c.y-=a.J[1]):(c.x-=parseInt(a.G/2,10),c.y-=parseInt(a.i/2,10));return c}
d.O=function(){if(this.L){var a=C(this,this.f);this.c.style.top=a.y+"px";this.c.style.left=a.x+"px"}};function B(a){a.c&&(a.c.style.display="none");a.L=!1}d.show=function(){if(this.c){var a=C(this,this.f);this.c.style.cssText=D(this,a);this.c.style.display=""}this.L=!0};d.remove=function(){this.a=null};d.Aa=function(){this.c&&this.c.parentNode&&(B(this),this.c.parentNode.removeChild(this.c),this.c=null)};
function D(a,b){var c=[];c.push("background-image:url("+a.Ga+");");c.push("background-position:"+(a.X?a.X:"0 0")+";");"object"===typeof a.g?("number"===typeof a.g[0]&&0<a.g[0]&&a.g[0]<a.i?c.push("height:"+(a.i-a.g[0])+"px; padding-top:"+a.g[0]+"px;"):"number"===typeof a.g[0]&&0>a.g[0]&&-a.g[0]<a.i?c.push("height:"+a.i+"px; line-height:"+(a.i+a.g[0])+"px;"):c.push("height:"+a.i+"px; line-height:"+a.i+"px;"),"number"===typeof a.g[1]&&0<a.g[1]&&a.g[1]<a.G?c.push("width:"+(a.G-a.g[1])+"px; padding-left:"+
a.g[1]+"px;"):c.push("width:"+a.G+"px; text-align:center;")):c.push("height:"+a.i+"px; line-height:"+a.i+"px; width:"+a.G+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.ka?a.ka:"black")+"; position:absolute; font-size:"+(a.la?a.la:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=f;f.prototype.addMarker=f.prototype.H;f.prototype.addMarkers=f.prototype.W;f.prototype.clearMarkers=f.prototype.qa;
f.prototype.fitMapToMarkers=f.prototype.sa;f.prototype.getCalculator=f.prototype.aa;f.prototype.getGridSize=f.prototype.ca;f.prototype.getExtendedBounds=f.prototype.P;f.prototype.getMap=f.prototype.C;f.prototype.getMarkers=f.prototype.D;f.prototype.getMaxZoom=f.prototype.da;f.prototype.getStyles=f.prototype.R;f.prototype.getTotalClusters=f.prototype.wa;f.prototype.getTotalMarkers=f.prototype.xa;f.prototype.redraw=f.prototype.s;f.prototype.removeMarker=f.prototype.Ba;f.prototype.removeMarkers=f.prototype.Ca;
f.prototype.resetViewport=f.prototype.A;f.prototype.repaint=f.prototype.ja;f.prototype.setCalculator=f.prototype.Da;f.prototype.setGridSize=f.prototype.Ea;f.prototype.setMaxZoom=f.prototype.Fa;f.prototype.onAdd=f.prototype.S;f.prototype.draw=f.prototype.O;u.prototype.getCenter=u.prototype.ba;u.prototype.getSize=u.prototype.va;u.prototype.getMarkers=u.prototype.D;v.prototype.onAdd=v.prototype.S;v.prototype.draw=v.prototype.O;v.prototype.onRemove=v.prototype.Aa;
